### ISSUE TITLE
hasAndBelongsToMany() with include syntax (again)

### ISSUE THREAD

**Issue by mshick** [1602/jugglingdb#367]
Sorry to open another ticket for this, but I've been stepping my way through the code and can confirm that this is not working as it should be. 

`lib/include.js` seems to be invoking the adapter's "all" method with a mismatched model & filter when attempting to load relationships generated via `hasAndBelongsToMany()`. The issue seems to be that it is skipping relation table, and attempting to load the related items directly.

So, for instance, in the jugglingdb-rethink adapter I am using, when attempting:

```
Post = schema.define('Post', ...);
Post.hasAndBelongsToMany('assets');
Post.all({ include: ['assets'] }, callback);
```

The rethink adapter gets the following params passed to it:

```
RethinkDB.prototype.all = function all(model, filter, callback) {
// model = 'Asset'
// filter.where = { postId: 
//   { inq: 
//      [ '6a48cc99-dd5c-49e0-9e04-8d91b62eaa69',
//        '6dd1657d-e7b7-4de5-b1d5-8d1294157189' ] }
```

That `filter.where` obj is correct if run on the relation table, `PostAsset` but is invalid when run on the `Asset` table that is being provided. 

When using the other approach to this, a standard relation, ie `post.assets(err, results)`, the relation table is invoked, and my related assets are found as I'd expect.

This is basically a dupe issue of the one I opened here, but I'm not certain this is a bug and not my general ignorance: https://github.com/1602/jugglingdb/issues/358

I do hope I can come up with a fix and submit a PR for this...

**Comment by odupuy** [comment]
Should it be closed as the PR is merged?
