### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by ramstein74** [1602/jugglingdb#437]
i see some issues to be answered and last commit 4 months ago,

Is this project dead ?

**Comment by roblabla** [comment]
Also http://ww1.jugglingdb.co/ is down :(

**Comment by leorossi** [comment]
Unfortunately it seems like...

**Comment by rezen** [comment]
@ramstein74 check out https://github.com/biggora/caminte - it's similar and active.

**Comment by 1602** [comment]
Nope, not dead. It was in coma (actually, just working good enough to not introduce any new code). Now coming back with new stuff: frozen immutable models, promises and revisited  lifecycle.

**Comment by alexiskattan** [comment]
compound is working.  Amazing if it got a some love too :+1:  keep up the amazing work
