### ISSUE TITLE
Potentially unhandled rejection [2] TypeError, when upgrading to new version of node.

### ISSUE THREAD

**Issue by alexiskattan** [1602/jugglingdb#438]
I have been using an older version of node (0.10.12).  When I upgraded to a modern version, I get a few errors.  

```
Potentially unhandled rejection [2] TypeError: _this.[classname].toObject is not a function
  at .......\node_modules\jugglingdb\lib\model.js:1003:21
```

`toObject`  does not seem to work anymore.  Anyone have an idea about how to fix it?  Thank you.

**Comment by 1602** [comment]
This is fixed. Jugglingdb is working fine on latest (4,5,6 node versions)
