### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by alexiskattan** [1602/jugglingdb#439]
http://ww1.jugglingdb.co/ is down.  Any chance to get it back up so we can view the documentation?

**Comment by Baggz** [comment]
:+1:

**Comment by chok** [comment]
As an alternative way, the doc is available in markdown in [docs folder](https://github.com/1602/jugglingdb/tree/master/docs). So you can view it formatted on github.

You can also build it with the makefile according the [about-docs section](https://github.com/1602/jugglingdb/blob/master/Makefile#L58)
