### ISSUE TITLE
Can i use JugglingDB in production?

### ISSUE THREAD

**Issue by EmpireWorld** [1602/jugglingdb#453]
Can i use JugglingDB in production?

**Comment by 1602** [comment]
The current version was heavily tested on production but retired a year ago. The new version is still under not so active development, only God knows when it will be completed. So, for now, I would not recommend using the legacy version in production unless you are willing to maintain it.

**Comment by EmpireWorld** [comment]
Thanks. so i can't use it now, right?

**Comment by randunel** [comment]
As it currently stands, it is usable, but no longer recommended for production, unless you are willing to support it yourself.

The project is not obsolete, but ready to be picked up by someone/anyone.

**Comment by EmpireWorld** [comment]
Thanks. i'm going to create one for myself.

All the bests.
