### ISSUE TITLE
process rpc message error TypeError: User.bulkUpdate is not a function

### ISSUE THREAD

**Issue by iniwap** [1602/jugglingdb#454]
IN MySQL this error

**Comment by 1602** [comment]
Could you try to use `User.update` instead?
Please let me know your `jugglingdb-mysql` adapter version and full stack trace of this error.

**Comment by iniwap** [comment]
{
  "_args": [
    [
      {
        "raw": "jugglingdb-mysql",
        "scope": null,
        "escapedName": "jugglingdb-mysql",
        "name": "jugglingdb-mysql",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "/Users/wangtingxuan/Documents/pomelo/lianqi/game-server"
    ]
  ],
  "_from": "jugglingdb-mysql@latest",
  "_id": "jugglingdb-mysql@0.2.3",
  "_inCache": true,
  "_location": "/jugglingdb-mysql",
  "_nodeVersion": "4.4.4",
  "_npmOperationalInternal": {
    "host": "packages-16-east.internal.npmjs.com",
    "tmp": "tmp/jugglingdb-mysql-0.2.3.tgz_1464943633666_0.9573445918504149"
  },
  "_npmUser": {
    "name": "anatoliy",
    "email": "rpm1602@gmail.com"
  },
  "_npmVersion": "2.15.1",
  "_phantomChildren": {
    "inflection": "1.2.7",
    "when": "3.7.3"
  },
  "_requested": {
    "raw": "jugglingdb-mysql",
    "scope": null,
    "escapedName": "jugglingdb-mysql",
    "name": "jugglingdb-mysql",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/jugglingdb-mysql/-/jugglingdb-mysql-0.2.3.tgz",
  "_shasum": "8c46af4c1018f0e7eb6e1c88adccc0b445a3d7d3",
  "_shrinkwrap": null,
  "_spec": "jugglingdb-mysql",
  "_where": "/Users/wangtingxuan/Documents/pomelo/lianqi/game-server",
  "author": {
    "name": "Anatoliy Chakkaev",
    "email": "mail@anatoliy.in"
  },
  "bugs": {
    "url": "https://github.com/jugglingdb/mysql-adapter/issues"
  },
  "dependencies": {
    "jugglingdb": "2.0.0-rc4",
    "mysql": ">= 2.0.0-alpha3",
    "uuid": "^2.0.1"
  },
  "description": "MySQL adapter for JugglingDB",
  "devDependencies": {
    "coffee-script": "latest",
    "mocha": "^2.4.3",
    "semicov": "~0.1.1-2",
    "should": "~3.0.1"
  },
  "directories": {},
  "dist": {
    "shasum": "8c46af4c1018f0e7eb6e1c88adccc0b445a3d7d3",
    "tarball": "https://registry.npmjs.org/jugglingdb-mysql/-/jugglingdb-mysql-0.2.3.tgz"
  },
  "gitHead": "3746a8f23752d1209098a2e6aadb55a76a29c210",
  "homepage": "https://github.com/jugglingdb/mysql-adapter",
  "license": "MIT",
  "main": "index.js",
  "maintainers": [
    {
      "name": "anatoliy",
      "email": "mail@anatoliy.in"
    }
  ],
  "name": "jugglingdb-mysql",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jugglingdb/mysql-adapter.git"
  },
  "scripts": {
    "test": "make test"
  },
  "version": "0.2.3"
}

**Comment by iniwap** [comment]
bulkUpdate   absolutely not exist!!!

**Comment by iniwap** [comment]
Using "npm install jugglingdb"  not the latest..and i solved it by using master
