### ISSUE TITLE
Enhancement: Multiple records on insert()

### ISSUE THREAD

**Issue by daball** [1602/jugglingdb#52]
Basically this is a non-issue, but would be a nice feature. If I could save multiple rows at once via an array (which with any good luck will run as a single transaction, depending on the driver), it would be useful.

Consider code:

```
var acc = require('./accounting'); //this has all the model stuff in it
acc.Ledger.create({name: 'General Ledger' }, function (err) {
  //debug: console.log(arguments);
  if (!err)
    console.log('Saved General Ledger');
  else if (err.code == '23505')
    console.log('General Ledger already exists');
  else {
    console.log('Error:', err.detail);
    return
  }
  //get general ledger
  acc.Ledger.all({ 'where': { 'name': 'General Ledger' }}, function (err, docs){
    if (err)
      console.log('Error:', err.detail);
    else {
      var genleg = docs[0];
      //this works:
      /*genleg.accounts.create({
          name: 'Assets'
        , baseType: 'Asset'
        , direction: 'debit'
        }, function (err, docs) {
          console.log(arguments);
      });*/
      //this fails:
      genleg.accounts.create(
        [
          {
            name: 'Assets'
          , baseType: 'Asset'
          , direction: 'debit'
          },
          {
            name: 'Liabilities'
          , baseType: 'Liability'
          , direction: 'credit'
          },
          {
            name: 'Equities'
          , baseType: 'Equity'
          , direction: 'credit'
          },
        ],
        function (err, docs) {
          console.log(arguments);
      });
    }
  });
});
```

The error provided is:

```
null value in column "name" violates not-null constraint
```

The error was probably due to the fact that it's looking for array['name'] but it doesn't exist (expected). So in order to permit this, some type of loop must be executed, either to devise multiple queries or to create a compound query, depending on each driver. You can figure out whether you have an array or not this way:

```
if (typeof objInput == 'object')
  if (objInput instanceof Object)
   //do this
  else if (objInput instanceof Array)
   //do that
```

After figuring out if it's an array or object, you could do one of two things. Split the code path as in above, or my favorite, force it to become an array and store the non-array in the first index. So:

```
if (typeof objInput == 'object' && objInput.prototype instanceof Array)
  //if not an array, make it an array
  objInput = [ objInput ];
for (var obj in objInput)
  //either run multiple single queries or
  //formulate a good INSERT ('A','B','C') VALUES( (1,2,3), (2,3,4) ) plan to run the query following the loop
```

Thanks, but I still haven't looked over the code enough to be comfortable butchering the code. I think you'll find this to be a useful feature as well, although it would probably require changes to every driver :~.

For my purposes of testing, I've been using postgres for this exercise. This may actually already exist in other drivers, as I haven't tested anything other than postgres.

Thanks,
David

**Comment by 1602** [comment]
This is implemented on js level now, without transactions yet.
